#!/bin/bash

AC_SET="powercfg /setacvalueindex scheme_current "
DC_SET="powercfg /setdcvalueindex scheme_current " 

GUID_SUB_CPU="SUB_PROCESSOR"
GUID_MINCPU="PROCTHROTTLEMIN"
GUID_MAXCPU="PROCTHROTTLEMAX"
GUID_PERFEPP="PERFEPP"
GUID_PERFEPP1="PERFEPP1"
GUID_PROCFREQMAX="PROCFREQMAX"
GUID_PROCFREQMAX1="PROCFREQMAX1"
# 0: disable 1: enable 2: auto
GUID_THROTTLING="THROTTLING"

GUID_SUB_IGPU="44f3beca-a7c0-460e-9df2-bb8b99e0cba6"
# 0: powersave 1: balance 2: performance
GUID_IGPU_BIAS="3619c3f2-afb2-4afc-b0e9-e7fef372de36"

GUID_SUB_GPU="SUB_GRAPHICS"
# 0: none 1: low power
GUID_GPU_POLICY="GPUPREFERENCEPOLICY"

DEFAULT=0
PERF=1
POWERSAVE=2
BALANCE=3
GAMING=4
LIMITED=5

#		DEF	PERF	PS	BALANCE	GAMING	LIMITED
AC_MINCPU=(	5 	0	0	0	0	0	)
AC_MAXCPU=(	100 	100	50	100	65	95	)
AC_PERFEPP=(	60 	0	100	50	50	50	)
AC_PERFEPP1=(	33 	0	100	50	50	50	)
AC_IGPU_BIAS=(	1 	2	0	2	2	2	)
AC_THROTTLE=(	2 	0	2	2	0	0	)
AC_GPUPOLICY=(	0 	0	0	0	0	0	)
AC_MAXFREQ=(	0	0	0	0	0x3e8	0	)
AC_MAXFREQ1=(	0	0	0	0	0x3e8	0	)

DC_MINCPU=(	5 	0	0	0	0	0	)
DC_MAXCPU=(	100 	100	50	100	65	95	)
DC_PERFEPP=(	80 	0	100	80	60	80	)
DC_PERFEPP1=(	50 	0	100	80	60	80	)
DC_IGPU_BIAS=(	1 	2	0	0	2	2	)
DC_THROTTLE=(	2 	2	2	2	2	2	)
DC_GPUPOLICY=(	0 	0	1	0	0	0	)
DC_MAXFREQ=(	0	0	0	0	0x3e8	0	)
DC_MAXFREQ1=(	0	0	0	0	0x3e8	0	)

if [ x$1 = x"" ]; then
	echo "<default/perf/powersave/balance/gaming>"
	exit 1
fi

case $1 in
	"default")
		PROFILE=${DEFAULT}
		;;

	"perf")
		PROFILE=${PERF}
		;;

	"powersave")
		PROFILE=${POWERSAVE}
		;;

	"balance")
		PROFILE=${BALANCE}
		;;

	"gaming")
		PROFILE=${GAMING}
		;;

	"limited")
		PROFILE=${LIMITED}
		;;

	*)
		echo "unknown profile \"$1\""
		exit 1
		;;
esac

set -x

${AC_SET} ${GUID_SUB_CPU} ${GUID_MINCPU} ${AC_MINCPU[PROFILE]}
${DC_SET} ${GUID_SUB_CPU} ${GUID_MINCPU} ${DC_MINCPU[PROFILE]}
${AC_SET} ${GUID_SUB_CPU} ${GUID_MAXCPU} ${AC_MAXCPU[PROFILE]}
${DC_SET} ${GUID_SUB_CPU} ${GUID_MAXCPU} ${DC_MAXCPU[PROFILE]}
${AC_SET} ${GUID_SUB_CPU} ${GUID_PROCFREQMAX} ${AC_MAXFREQ[PROFILE]}
${DC_SET} ${GUID_SUB_CPU} ${GUID_PROCFREQMAX} ${DC_MAXFREQ[PROFILE]}
${AC_SET} ${GUID_SUB_CPU} ${GUID_PROCFREQMAX1} ${AC_MAXFREQ1[PROFILE]}
${DC_SET} ${GUID_SUB_CPU} ${GUID_PROCFREQMAX1} ${DC_MAXFREQ1[PROFILE]}
${AC_SET} ${GUID_SUB_CPU} ${GUID_PERFEPP} ${AC_PERFEPP[PROFILE]}
${DC_SET} ${GUID_SUB_CPU} ${GUID_PERFEPP} ${DC_PERFEPP[PROFILE]}
${AC_SET} ${GUID_SUB_CPU} ${GUID_PERFEPP1} ${AC_PERFEPP1[PROFILE]}
${DC_SET} ${GUID_SUB_CPU} ${GUID_PERFEPP1} ${DC_PERFEPP1[PROFILE]}
${AC_SET} ${GUID_SUB_CPU} ${GUID_THROTTLING} ${AC_THROTTLE[PROFILE]}
${DC_SET} ${GUID_SUB_CPU} ${GUID_THROTTLING} ${DC_THROTTLE[PROFILE]}
${AC_SET} ${GUID_SUB_IGPU} ${GUID_IGPU_BIAS} ${AC_IGPU_BIAS[PROFILE]}
${DC_SET} ${GUID_SUB_IGPU} ${GUID_IGPU_BIAS} ${DC_IGPU_BIAS[PROFILE]}
${AC_SET} ${GUID_SUB_GPU} ${GUID_GPU_POLICY} ${AC_GPUPOLICY[PROFILE]}
${DC_SET} ${GUID_SUB_GPU} ${GUID_GPU_POLICY} ${DC_GPUPOLICY[PROFILE]}


powercfg /setactive scheme_current
